### ISSUE TITLE
Vertical scrollbar in the wrong position

### ISSUE THREAD

**Issue by chachan** [sgengler/atom-trello#2]
Hi, this is a snapshot when I scroll over a list of cards.

<img width="555" alt="screen_shot_2015-11-28_at_6_16_33_am" src="https://cloud.githubusercontent.com/assets/672094/11451798/f4b8dfea-9597-11e5-85cc-f6526e9762bb.png">

I'm using Atom 1.2.4 on OS X 10.11.1 (15B42). Let me know if you need more details about this

**Comment by sgengler** [comment]
Hey, I just pushed a fix, this should be resolved if you update the package. Needed overflow:hidden on the container. Fix here:  https://github.com/sgengler/atom-trello/commit/0130a2ed49f0dbaffaa9e3e69651220d9cf4a065#diff-b0680cdaa909ba4f41329d8b6ffc9fcf
